// FOREACH LOOP
// MAP METHOD
// FITER METHOD
// REDUCE METHOD
// FIND METHOD
// FIND INDEX
// SOME METHOD
// EVERY METHOD

// SELECTIONS IN HTML
// CLASSLIST IN JAVASCRIPT
// INSERTING ADJACENT HTML DYNAMICALLY IN A WEBPAGE
// TIMERS IN JAVASCRIPT
// SET TIMEOUT METHOD
// CLEAR TIMEOUT METHOD
// SET INTERVAL METHOD
// CLEAR INTERVAL METHOD
